DICE_NAMES = '/home/mauro/Workspace/dvision/gym/dice/darknet-master/data/dice.names'
DICE_CFG = '/home/mauro/Workspace/dvision/gym/dice/darknet-master/cfg/dice.cfg'
DICE_WEIGHTS = '/home/mauro/Workspace/dvision/gym/dice/darknet-master/backup/yolo-dice_14000.weights'
D4_CFG = ''
D4_WEIGHTS = ''